export const GET_WEATHER_DATA_REQUEST = 'GET_WEATHER_DATA_REQUEST'
export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS'
export const GET_WEATHER_DATA_FAILURE = 'GET_WEATHER_DATA_FAILURE'
export const SHOW_FORECAST = 'SHOW_FORECAST'


